### ISSUE TITLE
lua 5.2, using luarocks to install LuaSocket on MacOS X 10.10, lua script can not run correctly

### ISSUE THREAD

**Issue by zcfrank1st** [lunarmodules/luasocket#121]
When I finish install LuaSocket and run my code, the error occurs:

lua: error loading module 'lcurl' from file '/usr/local/lib/lua/5.2/lcurl.so':
    dlopen(/usr/local/lib/lua/5.2/lcurl.so, 6): Symbol not found: _luaL_typerror
  Referenced from: /usr/local/lib/lua/5.2/lcurl.so
  Expected in: dynamic lookup

stack traceback:
    [C]: in ?
    [C]: in function 'require'
    web.lua:1: in main chunk
    [C]: in ?

**Comment by ewestbrook** [comment]
Is there still a problem to be solved here?

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!
