### ISSUE TITLE
x64 support

### ISSUE THREAD

**Issue by Neustradamus** [lunarmodules/luasocket#125]
It works for x64 machines?

**Comment by diegonehab** [comment]
Should. Doesn't it?

**Comment by albfan** [comment]
See this

https://github.com/pkulchenko/ZeroBraneStudio/issues/500

Is it possible to upload sources for luasocket 2.x and instructions to compile it on 64 bits?

**Comment by diegonehab** [comment]
What do you mean? There is nothing peculiar about compiling LuaSocket for 64 bits on any platform.

**Comment by albfan** [comment]
What about tags for version 2.x? I don't know exactly what commit to use

**Comment by alerque** [comment]
Use the currently released versions. They work on 64 bit platforms just fine. If there are any specific current problems feel free to report them, but as far as I can tell there is nothing actionable in this issue.
