### ISSUE TITLE
Numerous problems with make PLAT=win32

### ISSUE THREAD

**Issue by TheCycoONE** [lunarmodules/luasocket#142]
I was eventually able to compile with the makefile for PLAT=win32 but I had to make a few changes to the make file and provide a few overrides to do it:

In src/makefile:
First, there is a reference to LUASOCKET_CFLAGS, which is undefined.  This should be CFLAGS_win32 (https://github.com/diegonehab/luasocket/blob/321c0c9b1f7b6b83cd83b58e7e259f53eca69373/src/makefile#L228)
Second, the LDFLAGS specify MACHINE:X86, which is unnecessary and prevents building against x64. I simply removed this flag (https://github.com/diegonehab/luasocket/blob/321c0c9b1f7b6b83cd83b58e7e259f53eca69373/src/makefile#L220)
Finally, having the version number after the .dll causes the linker not to generate the dll at all. For this I just overrode SOCKET_SO and MIME_SO when specifying make. (https://github.com/diegonehab/luasocket/blob/321c0c9b1f7b6b83cd83b58e7e259f53eca69373/src/makefile#L237)

Ultimately documentation would go a long way to helping the process as well. For reference I used msys2 launched from the visual studio x64 tools command prompt.

**Comment by alerque** [comment]
I checked the current makefile and these issues seem to have been dealt with. For example the line that used to be hard coded as `LUASOCKET_CFLAGS` is now `CFLAGS`, and `CFLAGS` is defined as `CFLAGS_$(PLAT)`. This was actually done in bce60be which predates this report, but apparently the breakage you linked to in 2015 got added sometime in that time frame and then reverted to the original working system.

As a reference our CI is now checking Windows builds and works with minimal differences in build commands across platforms. Like zero differences.

If there is still something relevant that is broken I'd be happy to look into it further, but it seems like this is no longer an issue.
