### ISSUE TITLE
MSVS Express 2015 Solution error

### ISSUE THREAD

**Issue by oskude** [lunarmodules/luasocket#151]
When i open the luasocket.sln in Microsoft Visual Studio Express 2015 for Windows Desktop, i get a popup with "One or more projects in the solution were not loaded correctly. Please see the Output Window for details."

But in the Output Window is only:

```
D:\downloads\luasocket-master\luasocket-master\socket.vcxproj : error  : One or more errors occurred.

D:\downloads\luasocket-master\luasocket-master\mime.vcxproj : error  : One or more errors occurred.
```

Where can i find more info what went wrong?
Can someone else open (and build) luasocket.sln with MSVS Express 2015?

ps. FWIW, i'm on ms-windows 7 64bit

**Comment by Stanzilla** [comment]
Same here. @diegonehab are you still maintaining this project?

**Comment by ewestbrook** [comment]
Are you still experiencing this issue?  Did the reference above help you?  Please let us know if action is needed.

**Comment by oskude** [comment]
sorry, lost track of this.
im not using this anymore. can be closed (i left it open for @Stanzilla)

**Comment by Stanzilla** [comment]
I'm not using it anymore either, can be closed I guess

**Comment by ewestbrook** [comment]
Thank you!
