### ISSUE TITLE
Update website to reflect repository changes

### ISSUE THREAD

**Issue by Babbleshack** [lunarmodules/luasocket#164]
I spent quite alot of time today, trying to get luasockets to compile with lua5.2, and it was because I was using an older version of luasockets from [the project page](http://w3.impa.br/~diego/software/luasocket/) furthermore I found a cloned page at [luatex](http://www.luatex.org/svn/trunk/source/texk/web2c/luatexdir/luasocket/doc/) which claims to be compatible with lua 5.2, however this was not the case; and finally I found [a version as a release from this repo](https://github.com/diegonehab/luasocket/downloads) which was also outdated.

I finally got the latest version from the repository zip.

**Comment by alerque** [comment]
Yup yup the website/docs are a bit out of date. c.f. #357.
