### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by n0la** [lunarmodules/luasocket#168]
As a downstream maintainer of lua ports a new tagged release would be really helpful.

**Comment by ncopa** [comment]
completely agree. last release, `v3.0-r1` was from 2013.

even just tagging `v3.0-r2` would be very helpful.

**Comment by mrueg** [comment]
@diegonehab any plans for a new release?

**Comment by Nehmulos** [comment]
Hello, I'm bumping this since there has recently been confusion on the [Guix](https://www.gnu.org/software/guix/) [mailing list](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29562#8).
Having a commit tagged as stable release would be much appreciated.

**Comment by Neustradamus** [comment]
Linked to https://github.com/diegonehab/luasocket/issues/93

**Comment by diegonehab** [comment]
I keep needing help on this. If you guys think it would be best to simply tag this as r2, we can certainly do this.

Are there any open issues that we should close before we tag?

**Comment by n0la** [comment]
I sadly can no longer really help you there. In the three years since I have made this issue I have moved on from lua programming as a whole. But another rc can't hurt, I'd say.

**Comment by TimWolla** [comment]
> If you guys think it would be best to simply tag this as r2, we can certainly do this.

At least the Debian project is already using a [non-tagged version from 2016](https://github.com/diegonehab/luasocket/commit/ac3201d) as indicated in the version number `3.0~rc1+git+ac3201d-4`: https://packages.debian.org/de/sid/lua-socket

So a tag clearly would be an improved over an arbitrary version that happened to be current when packaging. See the news timeline: https://tracker.debian.org/pkg/luasocket

**Comment by alerque** [comment]
Another downstream having issues with not having tags and luarocks RC release being 6 moths old. Can we please have a tagged release and publish a luarock that isn's labeled "rc"?

**Comment by Neustradamus** [comment]
@diegonehab?

**Comment by diegonehab** [comment]
Hey guys. My first child has just been born. If anybody picks does the work of a release, I can review and accept pull request. @ewestbrook can perhaps also help?

**Comment by ewestbrook** [comment]
Sure can.

And congratulations!

**Comment by alerque** [comment]
3 years ago I complained. Now I'm responsible for making it happen — and my second daughter is due in a few days so no crazy promises about timeline!

That being said I don't think there is anything in particular this issue is tracking. If you want notifications of releases you can subscribe to just release notices on GitHub. Since this doesn't track any release details other than "when release?" I'm going to close it.
