### ISSUE TITLE
too many C levels (limit is 200) in function at line 84 near 'chunk'

### ISSUE THREAD

**Issue by amochkin** [lunarmodules/luasocket#191]
Hi, after installing luasocket using luarocks on MacOS 10.12.1 (Sierra) got this error:

```
lua: /usr/local/share/lua/5.2/luarocks/loader.lua:117: error loading module 'socket' from file '/usr/local/share/lua/5.2/socket.lua':
    /usr/local/share/lua/5.2/socket.lua:88: too many C levels (limit is 200) in function at line 84 near 'chunk'
```

**Comment by diegonehab** [comment]
I'm not sure what is causing this error since I don't use LuaRocks. :/ @mascarenhas, can you help?

**Comment by mascarenhas** [comment]
This is a Lua parser error for too much syntactical nesting, which is odd. @amochkin, could you post your luarocks/loader.lua and socket.lua here?

**Comment by ewestbrook** [comment]
Is this still a problem?  Is the requested information forthcoming?

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!
