### ISSUE TITLE
No support for abstract namespace?

### ISSUE THREAD

**Issue by tkim5574** [lunarmodules/luasocket#216]
#I saw that this module supports unix socket and I've been trying to use it with abstract address. 

The below is the example code I tried:
address = '\0/var'
sock = socket.unix()
sock:connect(address)
which results in invalid argument.

Is there no support for abstract address?

**Comment by diegonehab** [comment]
It would need to be added because we end up using strlen() to compute the size of the path string. The modifications seem simple, in unixdgram.c and unixstream.c. If you send a pull request, I'll merge it.

**Comment by tkim5574** [comment]
Will work on it soon
