### ISSUE TITLE
release tag v3.0-rc2 vanished

### ISSUE THREAD

**Issue by bauen1** [lunarmodules/luasocket#218]
There appears to have been a release tag v3.0-rc2, but it vanished.
Can we have another release candidate for package scripts ?
The v3.0-rc1 tag is 4 years old and specifically the addition of MYCFLAGS and MYLDFLAGS is very usefull for packages.

**Comment by amery** [comment]
@bauen1 do you know what commit hash was v3.0-rc2?

**Comment by bauen1** [comment]
No

**Comment by diegonehab** [comment]
I don't recall deleting any tag. Is there evidence anywhere of its existence?

**Comment by amery** [comment]
@diegonehab in such case, what about tagging v3.0-rc3 now? :p

**Comment by bauen1** [comment]
https://github.com/diegonehab/luasocket/blob/316a9455b9cb4637fe6e62b20fbe05f5141fec54/rockspec/luasocket-3.0rc2-1.rockspec

**Comment by Neustradamus** [comment]
Linked to https://github.com/diegonehab/luasocket/issues/93

**Comment by alerque** [comment]
I believe (as an after-the-fact examination) that the rc2 rockspec was never officially released, instead an rc1 with rockrel 2 was released. A new series of releases should be along soon.

**Comment by Neustradamus** [comment]
@alerque: Time to create a 3.0 final?
- https://github.com/lunarmodules/luasocket/tags

**Comment by alerque** [comment]
We're working on it @Neustradamus.

**Comment by Neustradamus** [comment]
@alerque: Nice! :)

Linked to:
- https://github.com/lunarmodules/luasocket/issues/51
- https://github.com/lunarmodules/luasocket/issues/93
- https://github.com/lunarmodules/luasocket/issues/158
- https://github.com/lunarmodules/luasocket/issues/168
- https://github.com/lunarmodules/luasocket/issues/218
- https://github.com/lunarmodules/luasocket/issues/330
- https://github.com/lunarmodules/luasocket/pull/355
