### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by gut** [lunarmodules/luasocket#222]
I see a test directory and a "test" target on Makefile, but is there a complete test for this library?

I'm testing it on ppc64le (POWER8 machine) and when using the `tests/largetransfer.lua` from the `copas` project, it fails basically on the socket communication.

Please provide some shell script to run those tests, as it seems they need to run in parallel or alike.

**Comment by alerque** [comment]
The best reference would be the order we run all the test files in the CI workflow:

https://github.com/lunarmodules/luasocket/blob/master/.github/workflows/build.yml#L38-L50

With that question answered, I think I'll close this in favor of #227 which brings up more issues with the test suite and suggests adopting `busted`. I think that adaption is probably the best way forward so we'll track pulling the tests together into a proper suite there. In the mean time you can take a page out of the CI if you still need some tests.
