### ISSUE TITLE
Luarocks issue

### ISSUE THREAD

**Issue by RussDragon** [lunarmodules/luasocket#233]
There is a mistake in luarocks package (luarocks install luasocket), it installs luasocket with outdated http.lua which has TIMEOUT in global scope.

"apt-get install lua-socket" works well.

luarocks show luasocket:

> LuaSocket 3.0rc1-2 - Network support for the Lua language
> 
> LuaSocket is a Lua extension library that is composed by two parts: a C core
> that provides support for the TCP and UDP transport layers, and a set of Lua
> modules that add support for functionality commonly needed by applications that
> deal with the Internet.
> 
> License: 	MIT
> Homepage: 	http://luaforge.net/projects/luasocket/
> Installed in: 	/usr/local
> 
> Modules:
> 	ltn12 (/usr/local/share/lua/5.1/ltn12.lua)
> 	mime (/usr/local/share/lua/5.1/mime.lua)
> 	mime.core (/usr/local/lib/lua/5.1/mime/core.so)
> 	socket (/usr/local/share/lua/5.1/socket.lua)
> 	socket.core (/usr/local/lib/lua/5.1/socket/core.so)
> 	socket.ftp (/usr/local/share/lua/5.1/socket/ftp.lua)
> 	socket.headers (/usr/local/share/lua/5.1/socket/headers.lua)
> 	socket.http (/usr/local/share/lua/5.1/socket/http.lua)
> 	socket.serial (/usr/local/lib/lua/5.1/socket/serial.so)
> 	socket.smtp (/usr/local/share/lua/5.1/socket/smtp.lua)
> 	socket.tp (/usr/local/share/lua/5.1/socket/tp.lua)
> 	socket.unix (/usr/local/lib/lua/5.1/socket/unix.so)
> 	socket.url (/usr/local/share/lua/5.1/socket/url.lua)

**Comment by ewestbrook** [comment]
Confirmed.  The package being served by the LuaRocks server is quite old (and confusing, as they label it v3.0-rc2 but ship a file called v3.0-rc1.zip).

We'll get it sorted out with this upcoming release if not sooner.  I've registered with LuaRocks to streamling pushing a package to them when one is ready.

Also leaving this issue open for now for LuaRocks-specific release updates.
