### ISSUE TITLE
Will luasocket work on ARM64 platform

### ISSUE THREAD

**Issue by timusketeers** [lunarmodules/luasocket#276]
Does luasocket library support ARM64 platform and How should I change the makefile of luasocket to get a share library of it working on ARM64? I use the command “luarock install  luasocket 3.0-rc1” on ARM64 platform to generate the library of luasocket, but it seems not work. Any suggestion, thanks!

**Comment by ewestbrook** [comment]
Yes.  With LuaRocks, leave out the version, or use `3.0rc1-2`.  (We're preparing for a release, and in the mean time the LuaRocks upstream versioning is inconsistent.)  Alternatively, and to include recent fixes, clone the master branch from git and use `make PLAT=linux linux install`.  Both install methods work for me right now on Ubuntu Mate 16.04.5 LTS for Raspberry Pi `armv7l`.

**Comment by ewestbrook** [comment]
Sorry, just noticed that you actually said `ARM64`, and I don't have an `armv8` install handy.  But there are no known or expected issues, so please give it a go and let us know.

**Comment by timusketeers** [comment]
@ewestbrook , thanks for your message, I will try it. thanks

**Comment by ioiioo** [comment]
@ewestbrook  Please pay attention to this issues #333

**Comment by ewestbrook** [comment]
@ioiioo What do you want me to do?  I don't have a patch that fixes it.

**Comment by alerque** [comment]
This issue appears to have just been a question. If there is an actual bug or status report related to this we should have a dedicated issue to track it. There may be an issue, but since #333 has a specific log to work with I'm closing this as a question / duplicate.
