### ISSUE TITLE
Visual studio 2017 link errors

### ISSUE THREAD

**Issue by qfrtt** [lunarmodules/luasocket#287]
![image](https://user-images.githubusercontent.com/9437677/62141368-bded9200-b2ec-11e9-952f-31b27ece1faa.png)
Hi I am trying to compile it on Windows I already linked my luajit lib51.lib and switched to release mode x86 (same as the lib)

**Comment by alerque** [comment]
Does anybody currently have this issue? Or recognize what it was and how to solve it?

I know we're building successfully on Windows in CI but am not familiar with the landscape of possible compilers and IDEs to know what this issue involves.

**Comment by qfrtt** [comment]
this was solved years ago
