### ISSUE TITLE
How can I resolve the problem:options.c:324: error: `IPV6_V6ONLY' undeclared (first use in this function)

### ISSUE THREAD

**Issue by Achelics** [lunarmodules/luasocket#288]
when i use the mips toolchain to compile the luascoket, i met the errors.
the errors info:
inet.h:26: warning: ignoring #pragma GCC visibility
inet.h:53: warning: ignoring #pragma GCC visibility
**options.c: In function `opt_get_ip6_v6only':
options.c:324: error: `IPV6_V6ONLY' undeclared (first use in this function)
options.c:324: error: (Each undeclared identifier is reported only once
options.c:324: error: for each function it appears in.)
options.c: In function `opt_set_ip6_v6only':
options.c:329: error: `IPV6_V6ONLY' undeclared (first use in this function)
<builtin>: recipe for target 'options.o' failed**
make[1]: *** [options.o] Error 1
make[1]: Leaving directory '......'
makefile:382: recipe for target 'linux' failed
make: *** [linux] Error 2

How can I resolve it?
Thank you!

**Comment by alerque** [comment]
Does this still apply? Can you give some information about your platform, environment, and build system? I don't think there is enough to go on here to start tracking this down. Honestly it looks like this error is in some other header files on the system, not even in this module directly.

Closing for now, but please do comment back if there is any further info and I'll be happy to re-open and review.
