### ISSUE TITLE
Lua.socket installation o Mac osx Mojave fails. 

### ISSUE THREAD

**Issue by Josue198s** [lunarmodules/luasocket#290]
DRFS-GSs-MacBook:luasocket drfs_gs$ make macosx
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src macosx
/Applications/Xcode.app/Contents/Developer/usr/bin/make all-unix PLAT=macosx
gcc  -I/opt/local/include/lua/5.1 -I/opt/local/include/lua5.1 -I/opt/local/include/lua-5.1 -DLUASOCKET_NODEBUG -DUNIX_HAS_SUN_LEN -Wall -O2 -fno-common   -c -o luasocket.o luasocket.c
In file included from luasocket.c:15:
./luasocket.h:27:10: fatal error: 'lua.h' file not found
#include "lua.h"
         ^~~~~~~
1 error generated.
make[2]: *** [luasocket.o] Error 1
make[1]: *** [macosx] Error 2
make: *** [macosx] Error 2

**Comment by ewestbrook** [comment]
Here are two possible options -- both of which begin with knowing where your particular copy of lua.h has been installed.

1.  Use MYCFLAGS in your make command to instruct make to look in the additional location, e.g.
```
make -C src MYCFLAGS="-I/your/local/path" macosx
```

2.  Create a symbolic link in a place that is already searched for include files, e.g.
```
ln -sv /your/local/path/lua.h /usr/local/include/
```

**Comment by alerque** [comment]
It seems like this has probably been addressed. If there is anything current to be dealt with here feel free to bring up specifics.
