### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by ghost** [lunarmodules/luasocket#291]
I can make a request like this:

~~~lua
require('socket.http').request {
   url = 'http://speedtest.lax.hivelocity.net',
   sink = require('ltn12').sink.file(io.open('index.html', 'w'))
}
~~~

but if I use a larger file:

http://speedtest.lax.hivelocity.net/100mb.file

It has no progress. Compare with PHP:

~~~php
$v1 = curl_init('http://speedtest.lax.hivelocity.net/100mb.file');
$f1 = fopen('100mb.file', 'w');
curl_setopt($v1, CURLOPT_FILE, $f1);
curl_setopt($v1, CURLOPT_NOPROGRESS, false);
curl_exec($v1);
~~~

**Comment by alerque** [comment]
See the [Final considerations](https://github.com/lunarmodules/luasocket/blob/master/ltn012.md#final-considerations) section for some notes on using filters to create a progress counter.
