### ISSUE TITLE
lua 5.4 out, it is compatible?

### ISSUE THREAD

**Issue by Neustradamus** [lunarmodules/luasocket#317]
For information: https://www.lua.org/versions.html#5.4

**Comment by pkulchenko** [comment]
I've been using `luasocket-3.0-rc1` with Lua 5.4 and haven't seen any issues so far (other than ltn12 check for `module` that doesn't play nice with `strict`, but it's not Lua 5.4-related).

**Comment by alerque** [comment]
This played pretty nicely with Lua 5.4 up until the 5.4.3 release, now there is some trouble. I believe #334 addresses the last of it, but I would consider it pretty urgent to get that merged and a patch release cut.
