### ISSUE TITLE
Please ship `mbox.lua` in rock

### ISSUE THREAD

**Issue by rrthomas** [lunarmodules/luasocket#324]
This useful module is shipped by Debian, for example, but not in the LuaRock. It seems to be the only Lua module in the sources that is not shipped.

**Comment by Tieske** [comment]
(asking since it is not documented)

**Comment by rrthomas** [comment]
It parses [mbox](https://en.wikipedia.org/wiki/Mbox) files.

**Comment by alerque** [comment]
Pardon me if I'm being dense, but why is a networking / socket library a good home for a file format parser? That sounds like something that should have a different home. Parsing an over the while protocol is one thing, parsing an on disk file format seems to me to be a category error. What utility does Debian get out of it being in this package?

**Comment by alerque** [comment]
Having looked this over I am still of the opinion that it should be broken out into a different rock ... but in the mean time given the way we are using it for tests and the example code that provides I think it's entirely reasonable to ship it with the rock until such a time as it can be reasonably installed as a dependency from Luarocks.

**Comment by rrthomas** [comment]
Thanks for doing this!
