### ISSUE TITLE
No `v3.0-rc2` tag is available but the rockspec points to it.

### ISSUE THREAD

**Issue by E-Fir** [lunarmodules/luasocket#330]
https://github.com/diegonehab/luasocket/blob/master/rockspec/luasocket-3.0rc2-1.rockspec points to tag `v3.0-rc2` but I see only `v3.0-rc1` available in https://github.com/diegonehab/luasocket/tags

**Comment by alerque** [comment]
There is no rc2. I am guessing the rockspec currently in the repo was in *anticipation* of such a thing.

For now use the rockspec [published to LuaRocks](https://luarocks.org/modules/luasocket/luasocket) here: e.g. [luasocket-3.0rc1-2.rockspec](https://luarocks.org/manifests/luasocket/luasocket-3.0rc1-2.rockspec) as they actually link to right tag(s).

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/lunarmodules/luasocket/issues/51
- https://github.com/lunarmodules/luasocket/issues/93
- https://github.com/lunarmodules/luasocket/issues/158
- https://github.com/lunarmodules/luasocket/issues/168
- https://github.com/lunarmodules/luasocket/issues/218
- https://github.com/lunarmodules/luasocket/pull/355
