### ISSUE TITLE
HTTP calls do not work with lua 5.4.3

### ISSUE THREAD

**Issue by shoeb751** [lunarmodules/luasocket#331]
# Luasocket bug with Lua 5.4.3

## Short Description

HTTP calls do not work with Luasocket 5.4.3 and luasocket.

## System Info

Lua: 5.4.3
Luasocket: LuaSocket 3.0-rc1
Distro Archlinux

## Test code:

Requires `lua-socket` and `lua-sec` to be installed.
If testing using lua5.3, then `lua53-socket` `lua53-sec` need to be installed.

```lua
local http = require "socket.http"

print("---")
print("Testing https")

print(http.request("https://ffl.shoeb.pw"))

print("---")
print("Testing http")


print(http.request("http://ffl.shoeb.pw"))

print("---")
print("End http")
```

## Expected output:

```shell
$ lua5.3 t2.lua 
---
Testing https
Welcome to ffl.shoeb.pw. We shall be serving you soon!!!        200     table: 0x55a7c9e0f4d0   HTTP/1.1 200 OK
---
Testing http
Welcome to ffl.shoeb.pw. We shall be serving you soon!!!        200     table: 0x55a7c9e06510   HTTP/1.1 200 OK
---
End http
```
## Observed output:
```shell
$ lua t2.lua 
---
Testing https
Welcome to ffl.shoeb.pw. We shall be serving you soon!!!        200     table: 0x5639643d1800   HTTP/1.1 200 OK
---
Testing http
lua: /usr/share/lua/5.4/socket/http.lua:54: bad argument #1 to 'receive' (string expected, got light userdata)
stack traceback:
        [C]: in function 'socket.http.request'
        t2.lua:12: in main chunk
        [C]: in ?
```

## Explanation

HTTP call does not work. Diving into the source code to see what might be the cause yields the line:

```
 50 local function receiveheaders(sock, headers)
 51     local line, name, value, err
 52     headers = headers or {}
 53     -- get first line
 54     line, err = sock:receive()
 55     if err then return nil, err end
 56     -- headers go until a blank line is found
 57     while line ~= "" do
```

As you can see in the above code block, line 54 does not pass any arguments, so the argument that is passed will be `self` because of the `:` used in the function call.

I can confirm that this was working before my recent update to lua 5.4.3
So, mostly the recent update is what broke it as luasocket has not been updated for quite some time now.

Not sure if there needs to be some support for 5.4.3 that needs to be built into luasocket

**Comment by shoeb751** [comment]
I can also confirm that this got broken in lua 5.4.3 and used to work with lua 5.4.0 - 5.4.2

To do this those lua versions were locally compiled and tested against.

**Comment by pkulchenko** [comment]
The fix is easy: all `receive()` calls in `http.lua` and `tp.lua` need to be replaced with `receive("*l")`.

Unfortunately this issue affects all clients that use `receive()` method from luasocket without parameters (which is a default).

**Comment by atealxt** [comment]
> The fix is easy: all `receive()` calls in `http.lua` and `tp.lua` need to be replaced with `receive("*l")`.
> 
> Unfortunately this issue affects all clients that use `receive()` method from luasocket without parameters (which is a default).

I tried [haproxytech / haproxy-lua-http ](https://github.com/haproxytech/haproxy-lua-http/blob/master/http.lua#L670) which use `receive("*l")` but still face issue:
```
http.lua:670: Expect a 'string' for the prefix 
```

**Comment by pkulchenko** [comment]
@atealxt, I'm not sure where this error is coming from, but try specifying an empty string as the second parameter (the prefix) to see if this helps: `receive("*l", "")`.

**Comment by maikaliu** [comment]
the default parameter for receive is not working
in buffer_meth_receive method of buffer.c , put const char* p = luaL_optstring(L, 2, "*l"); to the front of the method can solve this

**Comment by atan2005** [comment]
Finally, after update buffer.c file to the one as mentioned on https://github.com/brunoos/luasec/commit/34252fb10ad4038cf6bf713f4f4d1c21ee948812 or download buffer.c from https://github.com/brunoos/luasec/tree/master/src/luasocket (v1.0.2), this will make luasocket work with Lua 5.4.3.

On my Windows 10 Pro setup at c:\msys64\mingw64, I have to modify the src/makefile to remove /lua from LDIR_mingw?=lua/$(LUAV)/lua so that it is the same as CDIR_mingw?=lua/$(LUAV), so that it has the "directory structure" of https://w3.impa.br/~diego/software/luasocket/installation.html

I have also issued below for build & install:-
make LUAV=5.4 PLAT=mingw LUAINC_mingw_base=/mingw64/include LUALIB_mingw_base=/mingw64/lib LUAPREFIX_mingw=/mingw64/lib
make LUAV=5.4 PLAT=mingw LUAINC_mingw_base=/mingw64/include LUALIB_mingw_base=/mingw64/lib LUAPREFIX_mingw=/mingw64/lib install

**Comment by Zash** [comment]
Oh, or is it choking on the `luaL_Buffer`, which might end up in the stack slot 2? That would explain "got light userdata".

https://github.com/diegonehab/luasocket/blob/5b18e475f38fcf28429b1cc4b17baee3b9793a62/src/buffer.c#L107-L117

**Comment by pkulchenko** [comment]
@Zach, yes, that's the issue. I submitted a fix in #334, but the fix you're using should work as well.

**Comment by Zash** [comment]
@pkulchenko Oh sorry I must have scrolled past that PR. Subtly different behavior from what I did tho.

**Comment by Nomarian** [comment]
will this ever be patched or is luasocket abandoned?

**Comment by alerque** [comment]
@Nomarian It's not *quite* abandoned. Per #292 the original author is interested in another maintainer stepping up. I'm interested in doing that and we have several other people who are willing to help, but so far they haven't pulled the trigger and passed the buck. I do hope to get this patched up — this issue in particular has started to break some of my old projects and needs fixing urgently.

**Comment by daurnimator** [comment]
The repository is now under the lunarmodules github organisation. We should be able to move forward with a solution now.
