### ISSUE TITLE
Unable to install luasocket

### ISSUE THREAD

**Issue by flyingCodeMonkeys** [lunarmodules/luasocket#340]
Hello I am trying to install the luasocket for an haproxy authentication app. 
I am gettting an error saying "lua.h no such file or directory" 
`|In file included from luasocket.c:15:0:
luasocket.h:27:10: fatal error: lua.h: No such file or directory
 #include "lua.h"
          ^~~~~~~
compilation terminated.
make[2]: *** [luasocket.o] Error 1
make[1]: *** [linux] Error 2
`

**Comment by atan2005** [comment]
You need the lua headers and libraries in order to make luasocket. You can also make those from lua source codes from here: https://www.lua.org/ftp/#source

**Comment by BIuBOo** [comment]
I'm a beginner. Is There a full tutorial on how to build this? I have it cloned into Visual studio but don't know the next steps since I have never done this.
thanks in advance

**Comment by alerque** [comment]
@flyingCodeMonkeys The response from @atan2005 is correct, you just need Lua headers on your system matching the running default Lua version to compile C libraries such as this one. We're happy to help if you have further questions, but I think that is the gist of it.

@BluBOo You should just install via `luarocks install`, that should take care of the necessary installation. If there is something more specific you need not covered please open a unique issue
