### ISSUE TITLE
LuaSocket for lua5.1

### ISSUE THREAD

**Issue by jlukovic** [lunarmodules/luasocket#344]
Hi, I write receipt for luasocket, to include it in my yocto image. I need luasocket for luajit(lua5.1) and i need correct hash for that. Can you tell me which hash i should use?

**Comment by alerque** [comment]
This project needs to be compiled (typically using `luarocks`) for your target system (Lua version and other system libraries). This is not something provided by this upstream project.

**Comment by alerque** [comment]
I don't have any trouble with this on Lua 5.1 / Luajit using normal tooling (such as `luarocks` or my distro package manager) to install. If you actually have trouble to report please feel free to comment, but I don't see anything we need to do here.
