### ISSUE TITLE
install for lua binaries

### ISSUE THREAD

**Issue by natethemaker** [lunarmodules/luasocket#348]
i spent a long time looking for luasocket for Lua binaries I cant find it need advice in this

**Comment by alerque** [comment]
This project (like most Lua Rocks) does not provide binaries, it provides sources that can be compiled according to your system. The `luarocks` package manager takes care of the compiling for appropriate Lua versions and your system libraries. Some distributions also provide packages with binaries appropriate for those systems (Homebrew, Arch Linux, Debian, Nix, etc.).
