### ISSUE TITLE
Sumneko's Lua language server shows a warning for using a lowercased global variable

### ISSUE THREAD

**Issue by C3pa** [lunarmodules/luasocket#373]
[This ](https://github.com/lunarmodules/luasocket/blob/1d61853ab84f0724502205f45849c2347d6a49ac/src/ltn12.lua#L18)is the offending line.

![image](https://user-images.githubusercontent.com/41503714/161334914-6d300cc8-6be9-43ce-9592-7127c9cbc56f.png)

Since it uses EmmyLua for annotations, it doesn't recognize `-- luacheck: ignore`.

Some context: Sumneko's Lua language server is the most widely used extension in VS Code for Lua support. It would be nice if we didn't get that warning.

**Comment by C3pa** [comment]
I propose a solution to this issue in #374.

**Comment by alerque** [comment]
Is this the *only* thing EmmyLua complains about in the whole project? If so great. If not lets consider fixing them all at once instead of piecemeal.

**Comment by C3pa** [comment]
Good point. It didn't catch any others automatically, but I opened all the files from luasocket manually, and it caught this:

![image](https://user-images.githubusercontent.com/41503714/161394773-6096758f-18cf-4b4a-8792-6d4d46ceda61.png)

 I use LuaJIT, so inherently Lua 5.1.

**Comment by C3pa** [comment]
If I try opening the unzipped [release folder](https://github.com/lunarmodules/luasocket/releases/download/v3.0.0/luasocket-3.0.0-1.src.rock) I got a bunch of warnings. Most of those come from tests, where I get: `Global variable in lowercase initial, Did you miss `local` or misspell it?`

Here I appended the output with the warnings.
[warnings.txt](https://github.com/lunarmodules/luasocket/files/8403112/warnings.txt)

What do you think about these? I'd just ignore the warnings coming from tests.

As a note, if you want me to mark some of those to be ignored by EmmyLua, it has support for [ignoring warnings](https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations#diagnostic) for the entire file, the next line, and the current line. In addition, it supports explicitly specifying which type of diagnostics to ignore. So, we can work out what is the preferred way to mark that.

**Comment by C3pa** [comment]
> Good point. It didn't catch any others automatically, but I opened all the files from luasocket manually, and it caught this:
> 
> ![image](https://user-images.githubusercontent.com/41503714/161394773-6096758f-18cf-4b4a-8792-6d4d46ceda61.png)
> 
> I use LuaJIT, so inherently Lua 5.1. So, that means it won't complain about features deprecated in newer Lua versions.

How would you like me to handle this one? Isn't the second parameter, `getmetatable(self.sock)`, just discarded and can be removed?

**Comment by catwell** [comment]
This file (`https.lua`) is not part of luasocket afaik, it is part of luasec.

**Comment by C3pa** [comment]
My bad there.

**Comment by alerque** [comment]
So does that mean the only other warnings are in tests?

**Comment by C3pa** [comment]
Sorry if I wasn't clear enought, the most of them are in tests, not all of them. Here I split those warnings per folders of this project:
[test-warnings.txt](https://github.com/lunarmodules/luasocket/files/8404308/test-warnings.txt)
[etc-warnings.txt](https://github.com/lunarmodules/luasocket/files/8404309/etc-warnings.txt)
[gem-warnings.txt](https://github.com/lunarmodules/luasocket/files/8404310/gem-warnings.txt)
[samples-warnings.txt](https://github.com/lunarmodules/luasocket/files/8404311/samples-warnings.txt)
[src-warnings.txt](https://github.com/lunarmodules/luasocket/files/8404312/src-warnings.txt)

So, here is a small breakdown of those:
- As I said, the most are in \test\. 
- There are some in \samples\ and \etc\ folders. Almost all of these are: "Global variable in lowercase initial, Did you miss `local` or misspell it?", since all the functions in the examples are defined in global scope. In my project, these examples aren't shipped, so end users don't get these errors. I don't know if you bother fixing these.
- In \gem\ folder there are 3 different warnings:
 1. "Undefined global `gem`."
 2. "Undefined global `mime`.",
 3. "Global variable in lowercase initial, Did you miss `local` or misspell it?",
 I don't know what this folder, so can't say anything more about that.
-  There are some warnings in \src\ folder. I don't get these, except the one I handled in #374. In my project I don't get the others in part because I have LuaJIT (Lua 5.1), and on the other hand, because we don't ship mbox.lua.

Should I adress the other warnings?

**Comment by C3pa** [comment]
For reasoning why I closed this, see the related discussion in #374.
