### ISSUE TITLE
FreeBSD socketfile creation issue

### ISSUE THREAD

**Issue by karolyi** [lunarmodules/luasocket#380]
Hey,

coming from prosody on FreeBSD 13.1-RELEASE, I think we caught an error. Upon creating a socket file for admin_socket, the created socket file lacks the last character. As in, trying to use a filename `/socket.sock` will result in a creation of a `/socket.soc` file.

Code that tests/reproduces this on there:
`lua54 -e 'print(require("socket.unix").stream():bind("./socket.sock"))'`

The FreeBSD package version is `lua54-luasocket-3.0.0,1`, but it reports as `LuaSocket:      3.0-rc1`.

**Comment by alerque** [comment]
Thanks for the report. I'd be happy to push through a fix if we had one, so if you find where this is originating from please go ahead with a PR and I'll get out a patch release.

The issue with luasocket reporting the wrong version internally was fixed just after release, sorry about that.

I tried reproducing this on Linux and was unable to, your MWE works fine.

What locale are you running under? I wonder if we are running into some locale specific string handling issue in Lua. I can't think why FeeBSD would behave differently than Linux in this particular case.

**Comment by karolyi** [comment]
Hey,

I don't have much time, much less am I a Lua expert. @Zash on [xmpp:prosody@conference.prosody.im](xmpp:prosody@conference.prosody.im) helped me with the command line originally, and pointed out that the error might be here: https://github.com/lunarmodules/luasocket/blob/master/src/unixstream.c#L192-L200

I know C so with this knowledge, I can try and cobble something together (given I'll have time), and come up with a PR if that suffices.

I can't tell when this is gonna happen though, as I'm pretty busy with life and other work. But I guess I'm no exception with that.

**Comment by alerque** [comment]
That bit of code does look suspicious.

When you look into this also consider perhaps that the Lua `make_plat()` function in the rockspec might be defining `UNIX_HAS_SUN_LEN` incorrectly for BSD. I don't actually know in this case if it is fair do lump it in with unix or if it would be more like macosx or if we need to split that platform setting further.

Given that I'm testing on Linux only, it might also be useful if somebody with macOS can test your reproduction above and confirm whether it does or does not work correctly there. It's possible Darwin is as broken as BSD and one side of that ifdef has an off-by-one bug.

**Comment by karolyi** [comment]
I have a macbook pro as well (very rarely used, mostly for testing purposes), will check what gives there.

**Comment by alerque** [comment]
It would also be helpful to know if our existing test suite catches this. I just looked at CI and we *are* building and testing on macOS, but looking at the `bind("path")` examples we have I'm not 100% confident we are testing anything that would catch your problem. If not we should fix that.

Sorry the testing isn't cleaned up yet into a decent runner, but this script or series of commands run from the project root after build (`luarocks build --no-install`):

```sh
#!/usr/bin/env sh
set -e
cd test
lua hello.lua
lua testsrvr.lua > /dev/null &
lua testclnt.lua
lua stufftest.lua
lua excepttest.lua
lua test_bind.lua
lua test_getaddrinfo.lua
lua ltn12test.lua
lua mimetest.lua
lua urltest.lua
lua test_socket_error.lua
kill %1
```

**Comment by karolyi** [comment]
Hey,

slowly coming back to this, I have somewhat bad news: I sold my macbook pro.

Is there an OSX environment by any chance I can access for testing?

**Comment by bqv** [comment]
this was fixed in the port https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=268968

**Comment by karolyi** [comment]
Nice! One less problem for me.

**Comment by alerque** [comment]
@bqv Obviously we wouldn't do it exactly how that port is patched, but is the fix in general something we can upstream?

**Comment by bqv** [comment]
https://cgit.freebsd.org/ports/commit/?id=7b22ba2f41006419913adfab9cb4e47f27e96df1

It's a packaging issue really, though it might be nice if the build system autodetected freebsd?

**Comment by alerque** [comment]
If we need some sort of detection for `luarocks install` to work, then we should probably do that ever if the platform has packages available (so projects that use vendored libraries can run right).
