### ISSUE TITLE
Is there plan to support IPv6 on http.lua open() API ?

### ISSUE THREAD

**Issue by zhendongcmss** [lunarmodules/luasocket#381]
luasocket is widely used. [darklajid](https://github.com/darklajid) previously raised a pull request  https://github.com/lunarmodules/luasocket/pull/91 to call the appropriate tcp()/tcp6() function in http.lua according to the IP after DNS resolution, but this part of the code has not been merged, but the underlying C code has not been modified, whether the community Any plans to fix it?

**Comment by alerque** [comment]
I am not familiar with the actual usage involved here, but a quick review of the history suggests the PR you link was not merged directly, but a branch purporting to cover the same ground *was* merged. See 4110e41 and commits in that branch such as 9695b1.

I'm not sure exactly what you think is missing from that. I don't have time to hack on this on my own right now but I'd be happy to review and facilitate any PRs that need attention. If you need to fish something out of that PR that was never applied properly please go ahead and cherry pick it into a new branch and open a PR and I'll give it a look.

**Comment by alerque** [comment]
> Does this [4110e41](https://github.com/lunarmodules/luasocket/commit/4110e4125dace9df3a744067066e5dee62670561) code already release on luasocket ?

Yes. The changes in that merge are in master and are in the current release.

> I here is lists: ( 3.0rc1-2 verison is the latest )

No, rc1 is not the latest. v3.0.0 is the latest.

Can you confirm what version you are actually using? I actually don't know what the state of IPv6 support is from use in the field but it looks like it has at least been worked on and it does not sound like you are necessarily using the latest release at all.

**Comment by alerque** [comment]
> I mean [4110e41](https://github.com/lunarmodules/luasocket/commit/4110e4125dace9df3a744067066e5dee62670561) doesn't been included on `3.0rc1-2`, right ?

No, it was merged after that tag.

> we use luarocks to manage dependence, it can install the latest version is `3.0rc1-2`. But v3.0.0 doesn't on [luarocks.org](https://luarocks.org). can we upload v3.0.0 to [luarocks.org](https://luarocks.org) ?

[v3.0.0 has been on luarocks.org for 76 days.](https://luarocks.org/modules/lunarmodules/luasocket)

**Comment by alerque** [comment]
I'm happy to look into issues opened against the current code base and review PRs that add any missing features or fix bugs, but the issue here appears to be that you are using the 8 year old rc1 tag instead of the current version. Please update to the current release, then report any specific issues.
