### ISSUE TITLE
Requesting HTTPS over an HTTP proxy doesn't work

### ISSUE THREAD

**Issue by Max1Truc** [lunarmodules/luasocket#385]
When requesting an HTTPS url over an HTTP proxy, LuaSocket tries to initiate a TLS session with the proxy server.

This works with mitmproxy, but not with other proxies.

Is it intended behavior ?

Otherwise, I can submit a PR to use the HTTP create function when an HTTP proxy is used.

**Comment by alerque** [comment]
I don't have much time to research the current or correct behavior, but will help facilitate a PR if one comes. From reading the issue at least that situation does sound like a bug.

**Comment by Max1Truc** [comment]
It seems to me most clients requesting HTTPS over an HTTP proxy would simply ask for a TCP tunnel with `CONNECT`.

However, doing a `GET https://[...]`, like for HTTP over HTTP proxy, works on the proxies I tested.

**Comment by Tieske** [comment]
for inspiration; lua-resty-http does include proxy support; https://github.com/ledgetech/lua-resty-http

**Comment by Max1Truc** [comment]
Thanks for the insiration.

Some features lua-resty-http supports:
- Proxied HTTP is requested with a request like `GET http://...` while proxied HTTPS is requested with a `CONNECT host:port`
- Two different proxy settings when proxying HTTP or HTTPS
- A `no_proxy` setting, to specify which hosts shouldn't be reached over a proxy

For now, I do not intent to provide any of these features in the PR.

It seems sufficient to send a `GET https://...` to the proxy server. I just read the RFCs and it seems this does not break the specifications, but don't take my word for it.

I'll also test this against some proxies I find to check if this works in practice.

**Comment by flip-rossi** [comment]
Sorry to revive a long closed issue, but can anyone confirm this still works?

If I use Tinyproxy (which is HTTP only) I'm only able to connect to http://example.com, but not https://example.com, which fails silently. If I use mitmproxy like suggested I can connect to both, regardless whether I set the proxy address as `http://` or `https://`.

I'm using `LuaSocket 3.1.0` and `LuaSec 1.3.2` with luarocks.
