### ISSUE TITLE
http: relative redirection fails for https scheme

### ISSUE THREAD

**Issue by nheir** [lunarmodules/luasocket#393]
Given than the [`Location`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location) header can refer to relative url, the following code prevent relative https redirection

https://github.com/lunarmodules/luasocket/blob/26b524e1d7b9a00045882d3c0f25486485b1d6a8/src/http.lua#L298-L306

`scheme` is `nil` on relative url, I suggest to either use reqt as `default` parameter to `url.parse` (maybe side-effect to dig into first), or skip the downgrade test in this case, since the scheme is preserved by `tredirect` code anyway.

https://github.com/lunarmodules/luasocket/blob/26b524e1d7b9a00045882d3c0f25486485b1d6a8/src/http.lua#L325-L328

**Comment by alerque** [comment]
On a cursory review using `reqt` as a default sounds right to me, but I haven't dug into it or what the side effects might be. In any case I probably don't have the time to research it but I'll try to facilitate a PR if you or anybody can work one up for this. Making sure it gets tested would be nice too.

**Comment by nheir** [comment]
I can write a PR. Would it be ok to rewrite the `httptest.lua` to use https://httpbin.org (or any third party) ?
or do you prefer expose the function from `http.lua` to be tested outside ?

**Comment by Tieske** [comment]
using httpbin should be fine
