### ISSUE TITLE
Field _VERSION not updated when v3.1.0 was released

### ISSUE THREAD

**Issue by oktoberfest6** [lunarmodules/luasocket#401]
lua -e "print(require('socket')._VERSION)"
--> LuaSocket 3.0.0

Seems that luasocket.h has not been updated:
#define LUASOCKET_VERSION    "LuaSocket 3.0.0"

**Comment by edubart** [comment]
I confirm this. HTTP agent for requests shows as `LuaSocket 3.0.0`, while I am using 3.1.0.

**Comment by alerque** [comment]
This will have to be fixed when v3.1.1 or similar is released. There is no sane way to fix in in an old release without creating an inconsistent situation where distros that have packaged this have different code than others. I'll leave this open to track that we need to hunt down where that string came from when we release.

**Comment by tpimh** [comment]
Are there any plans for 3.1.1 release?
