### ISSUE TITLE
What is the correct way to use luarocks?

### ISSUE THREAD

**Issue by wushu037** [lunarmodules/luasocket#406]
I'm having two problems

1. some modules are downloaded with names that don't match the names used by require. E.g. `luarocks install luasocket` -> `require("socket")`
2. does luarocks offer the ability to manage multiple versions of a module? I didn't find a description.

This can be difficult when doing collaborative development and long term development. So:

1. do I need to add a file to the project that describes which modules are used in the project?
2. Since there is no version management, it is possible that everyone in the team installs a different version of the module at a different time, so should I put the module in the project directory?

I need to hear from the luarocks team.

**Comment by catwell** [comment]
I am unsure why you are opening this issue on luasocket, but:

- Yes sometimes modules have a different name that the rock, this is often the case with other languages as well.
- LuaRocks allows a single version of a module for a given project but you can have different sets of rocks in different projects.

To have a specific set of versions for a project across a team, you can create a rockspec and install with `--only-deps`

**Comment by wushu037** [comment]
@catwell Sorry, I asked in the wrong place. But thank you for your answer.
