### ISSUE TITLE
url.parse() doesn't correctly handle URL with no path component.

### ISSUE THREAD

**Issue by flrgh** [lunarmodules/luasocket#417]
Here we have a URL with a port component (`:8071`) and a query string component (`?token=xxx&type=http-bulk`) but with the path component left out:

```lua
local url = require "socket.url"

local parsed = url.parse("https://listener-eu.logz.io:8071?token=xxx&type=http-bulk")

print(require("inspect")(parsed))
```

Result:

```lua
{
  authority = "listener-eu.logz.io:8071?token=xxx&type=http-bulk",
  host = "listener-eu.logz.io",
  port = "8071?token=xxx&type=http-bulk",
  scheme = "https"
}
```

I feel like one of the following must be true (probably need to read through an RFC to know for sure):

* This is a valid URL, but it's not parsed correctly
* This is not a valid URL for $reasons (path is required when query string is used or... something), and it should be rejected with an error

---

ref: https://github.com/Kong/kong/issues/11931

**Comment by daurnimator** [comment]
At least trying with lpeg_patterns, it parses correctly:
```lua
uri_patts = require "lpeg_patterns.uri"
uri_patts.uri:match("https://listener-eu.logz.io:8071?token=xxx&type=http-bulk")
```
```
host	listener-eu.logz.io
port	8071
scheme	https
query	token=xxx&type=http-bulk
```

So I'm going to say it's indeed an issue with luasocket.

**Comment by tzssangglass** [comment]
> probably need to read through an RFC to know for sure

I read [RFC3986-Syntax Components](https://datatracker.ietf.org/doc/html/rfc3986#section-3), which mentions that 
- `The scheme and path components are required, though the path may be empty (no characters)`
- `If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character.`

```text
https://listener-eu.logz.io:8042?token=xxx&type=http-bulk
\___/   \______________________/ \______________________/
  |               |                        |       
scheme        authority                  query  


```

`https://listener-eu.logz.io:8071?token=xxx&type=http-bulk` matched 
- has `authority`, the path component can be empty(no characters)

**Comment by alerque** [comment]
Yes, this is evidently a bug. Even if the empty path was not valid the port can't have a query string in it!

Contributions welcome if anybody wants to jump in with a PR.
