### ISSUE TITLE
Are we ready to release?

### ISSUE THREAD

**Issue by diegonehab** [lunarmodules/luasocket#51]
I am reasonably happy with the current state of the code. Almost pulling the trigger for a release.

I guess we need to focus a bit on documentation. Can anybody help?

**Comment by Neustradamus** [comment]
Any news for 3.0?
-> Linked to https://github.com/diegonehab/luasocket/issues/93

**Comment by nebulousdog** [comment]
this project might be dead, last release was 2013, https://github.com/diegonehab/luasocket/releases

**Comment by diegonehab** [comment]
I have asked in the list for somebody else that is willing to take over the responsibility of keeping the project up to date. Nobody volunteered. So you guys are stuck with me. If anybody wants to go over the issues, identify the most serious ones, and organize other people to submit patches, I am more than happy to go over the resulting pull requests, provide feedback, vet them, and accept them. But I don't see anybody willing to do it. I started this project when I was still in college, more than 20 years ago. Never made a single cent out of it. Altruism has its limits.

**Comment by nebulousdog** [comment]
didnt mean to sound like I didnt appreciate it :) I had fun using luasocket when I was in college too.

**Comment by diegonehab** [comment]
Didn't mean to sound bitter. :) It was more like a plea for alternatives. I simply don't have the bandwidth to keep contributing to the project. Maybe somebody else has.

**Comment by ewestbrook** [comment]
I misunderstood -- I thought you were only asking for immediate open issues for this release.

I volunteer.

If it's okay with you, I'll put together a pre-release checklist today, and post it here for review, unless you think there's another venue or approach that's more appropriate.

**Comment by ewestbrook** [comment]
A comprehensive review of outstanding items is underway.  Please watch for discussion in the various items themselves (Issues and PRs) as we clear, close, and merge in preparation for release.  Please also continue to raise any relevant considerations for discussion and/or action.  With some luck, in the very near future we should be able to designate a release candidate for testing.  Stay tuned.
