### ISSUE TITLE
Tag prior releases

### ISSUE THREAD

**Issue by harningt** [lunarmodules/luasocket#62]
The repository lacks tags letting us know the status in relation to prior versions. These would be useful to any looking to work with the code integrating into other projects.

In my case, I'm looking to see what sort of changes I might have to make in LuaEvent to work with 3.0 series. I don't expect any, but w/ git-based diff and change tracking, it'd be a little easier.

**Comment by alerque** [comment]
This is obsolete even by the current status quo, but will also be more obsolete as future releases will be automated based on tags anyway.
