### ISSUE TITLE
please update website

### ISSUE THREAD

**Issue by capr** [lunarmodules/luasocket#92]
hi,

the docs at http://www.impa.br/~diego/software/luasocket are out of date.

one idea to avoid having to sync the site with github every time is to make it redirect to this url:

https://rawgithub.com/diegonehab/luasocket/master/doc/index.html

thanks.

**Comment by alerque** [comment]
Yup yup. Very out of date. Documentation contributions welcome!

I'm closing this as  a duplicate of a newer issue (#357), but same idea...
