### ISSUE TITLE
Source code for luasocket-2.0.2-lua-5.1.2-Win32-vc8.zip

### ISSUE THREAD

**Issue by anujaganath** [lunarmodules/luasocket#94]
HI,

I am a user of Koneki LDT and use luasocket library. Can you please point me to the source files for the mime/core.dll and socket/core.dll in the zip folder mentioned above. The luaforge.net mentions that the source files are available but I haven't seen them in the zip folder.
I have the above mentioned zip folder from:
http://files.luaforge.net/releases/luasocket/luasocket/luasocket-2.0.2
I would really appreciate your prompt response regarding pointers to this since this is blocking further progress in my project.

Thanks,
Anu

**Comment by ewestbrook** [comment]
Does anything need to be done here?

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!

**Comment by anujaganath** [comment]
Nothing to be done.

Thanks,
Anu
